services:
  seafile-samba-bridge:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: seafile-samba-bridge
    restart: unless-stopped
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    tmpfs:
      - ${CACHE_DIR:-/dev/shm/seadrive-cache}:size=${CACHE_SIZE_LIMIT:-10G},mode=1777
    volumes:
      - ${BASIC_STORAGE_PATH:-./}seafile-samba-meta:/var/lib/seadrive
    environment:
      - SEAFILE_URL=${SEAFILE_SERVER_PROTOCOL:-http}://${SEAFILE_SERVER_HOSTNAME:?Variable is not set or empty}
      - SEAFILE_USERNAME=${INIT_SEAFILE_ADMIN_EMAIL}
      - SEAFILE_PASSWORD=${INIT_SEAFILE_ADMIN_PASSWORD}
      - SEAFILE_TOKEN=${SEAFILE_TOKEN}
      - SEAFILE_IS_PRO=${SEAFILE_IS_PRO:-false}
      - CACHE_SIZE_LIMIT=${CACHE_SIZE_LIMIT:-10GB}
      - CACHE_DIR=${CACHE_DIR:-/dev/shm/seadrive-cache}
      - SAMBA_SHARE_NAME=${SAMBA_SHARE_NAME:-seafile_share}
      - SAMBA_USERNAME=${SAMBA_USERNAME:-seafile_user}
      - SAMBA_PASSWORD=${SAMBA_PASSWORD:?Variable is not set or empty}
      - CLIENT_NAME=${CLIENT_NAME:-docker-samba-bridge}
    ports:
      - ${SAMBA_PORT:-445}:445
    depends_on:
      seafile:
        condition: service_healthy
    networks:
      - seafile-net

networks:
  seafile-net:
    name: seafile-net
